package com.ham.onettsix.constant

object ExtraKey {
    const val PERMISSION_CLICK_SECTION = "PERMISSION_CLICK_TERMS"

    const val PERMISSION_CHECKED_TERMS = "PERMISSION_CHECKED_TERMS"

    const val PERMISSION_PRIVACY_POLICY = "PERMISSION_PRIVACY_POLICY"

    const val PERMISSION_ALARM_SWITCH = "PERMISSION_ALARM_SWITCH"

    const val TYPING_GAME_QUESTION_ID = "TYPING_GAME_QUESTION_ID"
    const val TYPING_GAME_EPISODE = "TYPING_GAME_EPISODE"
    const val TYPING_GAME_CONTENT = "TYPING_GAME_CONTENT"
    const val TYPING_GAME_IS_RANK_GAME = "TYPING_GAME_IS_RANK_GAME"


    const val YOUTUBE_ITEM_DATA = "YOUTUBE_ITEM_DATA"

}